apiVersion: v1
kind: Secret
metadata:
  name: ceph-s3-credentials
type: Opaque
stringData:
  access-key: AKIA****MASKED****
  secret-key: ****MASKED****
  endpoint: ceph-rgw.ceph-storage.svc.cluster.local:7480
  bucket: data-platform-bronze
